apt_update: true
apt_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [ docker ]
packages:
  - nfs-common
  - nginx
mounts:
  - ["eo-storage01.eodc:/", "/eodc1", "nfs4", "rw", "0", "0"]
  - ["eo-storage02.eodc:/", "/eodc2", "nfs4", "rw", "0", "0"]
write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    append: true
    content: |
      10.10.29.10     gateway
      10.10.29.11     node1
      10.250.23.242   eo-storage01.eodc
      10.250.23.231   eo-storage02.eodc
  - path: /var/www/html/index.html
    content: |
      <html>
      <body>
        <h1>Hello, World!</h1>
        <p>Welcome to the example web page!</p>
      </body>
      </html>      
    owner: 'root:root'
    permissions: '0644' 
manage_etc_hosts: true
runcmd:
  - mount -a # retry mount after edit of hosts