apt_update: true
apt_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [ docker ]
packages:
  - git
  - nginx
  - nfs-common
  - nfs-ganesha
mounts:
  - ["eo-storage01.eodc:/", "/eodc", "nfs4", "rw", "0", "0"]
write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    append: true
    content: |
      10.10.29.10     gateway
      10.10.29.11     app
      10.10.29.12     node1
      10.250.23.242   eo-storage01.eodc
      10.250.23.231   eo-storage02.eodc
manage_etc_hosts: true
runcmd:
  - mount -a # retry mount after edit of hosts
  
  # docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  # deploy stack
  - git clone https://github.com/EarthyScience/FAIRSenDD
  - cd FAIRSenDD/infrastructure/app
  - sudo docker compose up --build --detach