version: "3.8"
services:
  ogc_api:
    image: danlooo/fairsendd_ogc_api
    build: ../../ogc-api
    container_name: ogc_api
    ports:
      - "9001:80"
  website:
    image: danlooo/fairsendd_website
    build: ../../website
    container_name: website
    ports:
      - "9002:80"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - /data:/data
      - minio_config:/root/.minio
volumes:
  minio_config:
