version: "3.8"
services:
  ogc_api:
    image: danlooo/fairsendd_ogc_api
    build: ../../ogc-api
    container_name: ogc_api
    ports:
      - "9001:80"
  website:
    image: danlooo/fairsendd_website
    build: ../../website
    container_name: website
    ports:
      - "9002:80"
