apt_update: true
apt_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [ docker ]
packages:
  - nfs-common
  - nfs-ganesha
mounts:
  - ["eo-storage01.eodc:/", "/eodc", "nfs4", "rw", "0", "0"]
write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    append: true
    content: |
      10.10.29.10     gateway
      10.10.29.11     app
      10.10.29.12     node1
      10.250.23.242   eo-storage01.eodc
      10.250.23.231   eo-storage02.eodc
  - path: /etc/exports
    content: |
      /eodc *(ro,sync,fsid=0)
manage_etc_hosts: true
runcmd:
  - mount -a # retry mount after edit of hosts