apt_update: true
apt_upgrade: true
packages:
  - nfs-common
  - nfs-ganesha

  # docker
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
mounts:
  - ["gateway:/eodc", "/eodc", "nfs4", "ro", "0", "0"]
  - ["/dev/vdc", "/data", "auto", "defaults"]
write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    append: true
    content: |
      10.10.29.10     gateway
      10.10.29.11     app
      10.10.29.12     node1
      10.250.23.242   eo-storage01.eodc
      10.250.23.231   eo-storage02.eodc
manage_etc_hosts: true
runcmd:
  # retry mount after edit of hosts
  - mount -a

  # docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin