name: Deploy apps
on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  deploy_apps:
    runs-on: self-hosted
    steps:
      - name: Write SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          host='app'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - uses: actions/checkout@v4
      - name: Deploy website
        run: |
          ssh app sh <<EOF

          cd FAIRSenDD
          git fetch
          git checkout ${{ github.sha }}

          cd website
          # render needs to be outside of docker build because docker is called itself
          rm -rf content/out.zarr || :
          ls content/*.qmd | xargs -i -P 4 quarto render {}     

          cd ../infrastructure/app
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKER_USERNAME }} --password-stdin
          docker compose build
          docker compose push
          docker compose up --detach
          EOF
