name: Deploy infrastructure
on: [push]
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      TF_VAR_application_credential_id: ${{ secrets.TF_VAR_application_credential_id }}
      TF_VAR_application_credential_secret: ${{ secrets.TF_VAR_application_credential_secret }}
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - uses: actions/checkout@v4
      - run: terraform -chdir=infrastructure init
      - run: terraform -chdir=infrastructure plan
