name: ogc_app_cwl
on:
  push:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
        with:
          submodules: "true"
      - uses: actions/setup-python@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker images
        run: |
          docker compose --project-directory ogc-app-cwl build --push && \
          TAG=latest docker compose --project-directory ogc-app-cwl build --push
        env:
          TAG: ${{ github.sha }}
      - run: pip install cwltool
      - name: Validate CWL workflow
        run: cwltool --validate ogc-app-cwl/fairsendd.cwl
      - name: Run test CWL workflow
        run: |
          cwltool ogc-app-cwl/fairsendd.cwl#rqa \
           --continent EU \
           --tiles E051N018T3 \
           --start-date 2021-01-01 \
           --end-date 2022-01-01 \
           --in-dir RQADeforestationTestData \
           --out-dir test1 \
           --access-key $AWS_ACCESS_KEY_ID \
           --secret-key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
