name: ogc_app_cwl
on:
  push:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
        with:
          submodules: "true"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push compiler docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:ogc-app-cwl/rqa"
          file: Dockerfile
          tags: danlooo/fairsendd_rqa:${{ github.sha }}, danlooo/fairsendd_rqa:latest

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"
          architecture: "x64"
      - run: pip install cwltool

      - name: Validate CWL workflow
        run: cwltool --validate ogc-app-cwl/fairsendd.cwl
      - name: Run test CWL workflow
        run: |
          cwltool ogc-app-cwl/fairsendd.cwl#rqa \
           --continent EU \
           --tiles E051N018T3 \
           --start-date 2021-01-01 \
           --end-date 2022-01-01 \
           --in-dir RQADeforestationTestData \
           --out-dir test1 \
           --access-key $AWS_ACCESS_KEY_ID \
           --secret-key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
